### PR TITLE
feat: improve accessibility

### PR DESCRIPTION
**Pull request by DaniAcu**
This PR is improving the accesibility and the paste behaivior of the component.

Changes:
- Add a aria-label
- Make the input hide visually but fully accesible by the browser. You could hover, focus or whatever and is directly in the input.

First this reduce the complexity to have a div with a button role (which is not what it is, because is a input. So the screen reader could start saying that is a button which confuse to our users). Then I replicate the styles of [input-otp](https://input-otp.rodz.dev/) to be able to copy and paste in mobile.

### CODE REVIEW

**Comment by VerburgtJimmy** [comment]
Hey thank you very much for this contribution. I just got back from vacation so excuse my late response. I will test this in the coming week and then probably include it in the next minor release if everything is ok.

**Review by VerburgtJimmy — CHANGES_REQUESTED** [review]
Hey there. I had the time today to check out your changes. The changes you made look good but you need to add a couple of things:

- As you changed the code in the routes page.svelte, please also change the README and the code.ts (you can find this in the routes folder) example code to reflect these same changes.
- As you made changes to the types.ts file. Please also update the README with the same changes for the API Reference section.

Everything looks and works good further so if you can add these things I can merge the changes and then prepare a new release. If you cannot, please also say so I can do these things myself. Thanks

**Comment by DaniAcu** [comment]
Hi thanks! I cloud do it tomorrow if it works for you. 😊

**Comment by VerburgtJimmy** [comment]
Sure, no problem!

**Review by VerburgtJimmy — CHANGES_REQUESTED** [review]
Hi, there is still one problem. In the README you have changed inputType to inputNumeric while in the earlier changes to the actual code you changed this to inputMode. Please change the readme to inputMode if that is your prefered name for this type. thanks!

**Comment by DaniAcu** [comment]
Haha 😂 my bad! I think that I fixed that. Thanks 😊

**Comment by VerburgtJimmy** [comment]
haha no problem. If you could commit those final changes than i will be able to publish the new version later today. Thanks!

**Comment by DaniAcu** [comment]
Done

**Review by VerburgtJimmy — APPROVED** [review]
Great thanks a lot for the whole contribution!

**Pull request merged**
